### ISSUE TITLE
LeakyRELU commented out in generator

### ISSUE THREAD

**Issue by MCFreddie777** [jordan-bird/art-DCGAN-Keras#1]
Hello, I just wanted to ask, what's the difference when the the LeakyRELU in generator is and isn't commented out?

**Comment by jordan-bird** [comment]
You can uncomment the line to apply a Leaky ReLU activation layer based on the findings of Radford et al. (2015) who found that it worked well, specifically noting stability for higher resolution output images. It allows for small negative values as opposed to ReLU where y is 0 if x is less than or equal to zero. LeakyReLU is given as: 
```
  f(x) = alpha * x if x < 0
  f(x) = x if x >= 0
```
In Keras, the default alpha value is 0.3, I tend to try out Leaky ReLU if the losses collapse and learning ceases. You can also replace this line with any activation function you want.


Radford, A., Metz, L., & Chintala, S. (2015). Unsupervised representation learning with deep convolutional generative adversarial networks. arXiv preprint arXiv:1511.06434.
https://arxiv.org/pdf/1511.06434.pdf (See the end of Section 3)
